project_id = "uuirvevhvjvnubihnstz"

[functions.password-reset-otp]
verify_jwt = false

[functions.financial-chat]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-card-payment]
verify_jwt = false

[functions.mercadopago-public-key]
verify_jwt = false

[functions.check-subscriptions]
verify_jwt = false

[functions.check-due-expenses]
verify_jwt = false

[functions.send-email-smtp]
verify_jwt = false
