// This file is automatically generated. Do not edit it directly.
// Force client reload for schema cache sync
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const createSupabaseClient = () =>
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export let supabase = createSupabaseClient();

// Allows recreating the client in runtime after schema changes.
export function recreateSupabaseClient() {
  supabase = createSupabaseClient();
  return supabase;
}
